### ISSUE TITLE
SwipeRefreshLayout in News/Mensa/Klausurenplan

### ISSUE THREAD

**Issue by LRAnimations** [Cedgetec/SchulinfoApp#30]
In den News, der Mensa und dem Klausurenplan sind die swipe down to refresh layouts ein klein wenig verbuggt und lösen halt aus, wenn man hochscrollt und oben  ankommt, eigentlich sollten sie nur auslösen, wenn man bereits oben ist und dann hochscrollen will

**Comment by Lennart16** [comment]
Ist das nicht schon behoben?

**Comment by Gebatzens** [comment]
@Lennart16 Nein, das exisitert tatsächlich immer noch. Zumindest in News und Mensa.

**Comment by Gebatzens** [comment]
Sollten das wirklich so sein? in Gmail ist das zum Beispiel auch nicht so.

**Comment by LRAnimations** [comment]
@Gebatzens Gmail ist vermutlich die einzige App von Google, bei der es nicht so ist. Allerdings ist es besser, als bei uns, da bei Gmail sobald man den oberen Rand erreicht hat, das swipe to refresh layout sich von oben nach unten runterziehen lässt. Bei uns ist es einfach plötzlich da und zwar bereits in vollkommen herunter gezogener Form.

**Comment by LRAnimations** [comment]
Ist mittlerweile behoben worden.
