### ISSUE TITLE
Add skip button to FirstUseActivity

### ISSUE THREAD

**Issue by asterix11** [Cedgetec/SchulinfoApp#41]
You may have to add a skip button to the FirstUseActivity, to allow users who only installed the APP on another device to skip the FirstUseActivity.

There may be users who click on "Skip" by accident, but these users are the users that would skip this FirstUseActivity anyway, which means that they will not read it and only swipe to find the "Get started" button.

**Comment by Gebatzens** [comment]
@LRAnimations do it now or tomorrow.

**Comment by Gebatzens** [comment]
It is not finished.

**Comment by asterix11** [comment]
Fix it today.
