### ISSUE TITLE
Unnecessary notifications at impossible times

### ISSUE THREAD

**Issue by Lennart16** [Cedgetec/SchulinfoApp#56]
The app woke me up at 3:38 in the morning stating the plan had been changed with notification, light and so on. But as I checked the schedule, it was obvious nothing got changed (No teacher would write an entry at 3:38 AM).

Apparently the problem occurs more often than I thought as several users reported it to me.
This problem has to be fixed very quickly because it's very annoying. Thank you.

![a24553c8ef1122b75ef67837606369d720b0b67c393e399232 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/10562711/11318036/fac2b1ae-9042-11e5-9a4f-4c28ef290888.jpg)

**Comment by Gebatzens** [comment]
Might be fixed server-side.

**Comment by Lennart16** [comment]
Sadly the messed up server sends them again............ I don't like it, that is really bad!!
