### ISSUE TITLE
App crashes while running in the background

### ISSUE THREAD

**Issue by Lennart16** [Cedgetec/SchulinfoAPP#57]
The app simply crashed as I was doing something else. Suddenly the "SchulinfoApp wurde beendet" notification appeared on my screen.

![e7c1bef979f5e549282321bbb7388b267b7806c7c8225d68aa pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/10562711/11318089/960253b2-9044-11e5-9ac4-ce37bcbfbf0b.jpg)

**Comment by Gebatzens** [comment]
Yes, see #55

**Comment by Lennart16** [comment]
Aha. Thanks.

**Comment by Gebatzens** [comment]
Fixed in c23feb39a5bddc07c921d0aa9cdd56b2c09c7684
